name: Build&Push -> Docker
on:
  schedule:
    - cron: "@monthly"
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: nixos
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_KEY }}

      #- name: Set up QEMU
      #  uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
        # used to create dated tag
      - name: Set date tag 
        id: date 
        run: echo "TAG=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Build and push container
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          pull: true
          #platforms:
          #  - linux/amd64
          #  - linux/arm64
          tags: |
            docker.io/jimurrito/har-surgeon:${{ steps.date.outputs.TAG }}
            docker.io/jimurrito/har-surgeon:latest
          

