name: Build&Push -> Forgejo
on:
  schedule:
    - cron: "@monthly"
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: nixos
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Forgejo registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.FORGEJO_REGISTRY_URL }}
          username: ${{ secrets.FORGEJO_REGISTRY_USER }}
          password: ${{ secrets.FORGEJO_REGISTRY_KEY }}

      #- name: Set up QEMU
      #  uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push har-surgeon
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          pull: true
          #platforms: |
          #  linux/amd64
          #  linux/arm64
          build-args: |
            MC_VERSION=1_21_1
          tags: forgejo.immerhouse.com/jimurrito/har_surgeon:latest

